---
global:
  query:
    name: FindResourcesWithProductLineAndSubline

experiments:
  - id: dev_env_current_gen_dop_pi_2023_ultim
    startDate: '2023-12-15'
    endDate: '2024-01-21'
    productLine: 'Domain Ownership Protection'
    productSubLine: 'Domain Ownership Protection'
    allocationDate: '2023-12-19'
    query:
      name: FindResourcesWithProductLineAndSubline2
      params: []

  - id: abn_vbp_poc_test_exp_2
    startDate: '2023-12-15'
    endDate: '2024-01-21'
    productLine: 'Domain Ownership Protection'
    productSubLine: 'Domain Ownership Protection'
    allocationDate: '2024-01-04'
